#pragma kernel Integrate

#include "../Common.hlsl"

StructuredBuffer<Particle> _ParticleBuffer;
RWStructuredBuffer<Particle> _ParticleBufferWrite;

float _DeltaTime;
float _NoiseScale;
float3 _SpaceMin;
float3 _SpaceMax;

[numthreads(256, 1, 1)]
void Integrate (uint3 id : SV_DispatchThreadID)
{
    uint pid = id.x;
    Particle p = _ParticleBuffer[pid];
    p.position += p.velocity * _DeltaTime;

    ClampPosition(p.position, _SpaceMin, _SpaceMax);
    
    _ParticleBufferWrite[pid] = p;
}
