#pragma kernel Integrate

#include "Common.hlsl"

StructuredBuffer<Particle> _ParticleBuffer;
RWStructuredBuffer<Particle> _ParticleBufferWrite;

float _DeltaTime;
float _NoiseScale;

[numthreads(256, 1, 1)]
void Integrate (uint3 id : SV_DispatchThreadID)
{
    uint pid = id.x;
    Particle p = _ParticleBuffer[pid];
    p.position += p.velocity * _DeltaTime;
    
    _ParticleBufferWrite[pid] = p;
}
